---
# First uninstall any unnecessary packages and ensure that aptitude is installed.
- name: 'Update apt cache'
  apt: update_cache=yes
- name: 'Ensure that aptitude and dependencies are installed'
  apt: name={{item}} state=present force=yes
  with_items:
  - aptitude
  - nano
  - lsb-release
  - sudo
  - python-apt
  - debconf
  - python-mysqldb
  - screen
- name: 'Purge unneeded server services (apache2, sendmail, bind9, nscd)'
  apt: name={{item}} state=absent force=yes purge=yes
  with_items:
  - nscd
  - bind9
  - sendmail
  - apache2
  - apache2.2-common
