# meta file for percona-server
---
galaxy_info:
  author: Mischa ter Smitten
  company: Oefenweb.nl B.V.
  description: Set up percona-server server in Debian-like systems
  license: MIT
  min_ansible_version: 1.9.6
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
    - name: Debian
      versions:
        - wheezy
        - jessie
  galaxy_tags:
    - system
    - database
    - database:sql
dependencies: []
