# tasks file for percona-server
---
- name: install | configure debconf
  debconf:
    name: "{{ item.name }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items: "{{ percona_server_debconf_selections }}"
  changed_when: false
  tags:
    - percona-server-install-configure-debconf

- name: install | dependencies
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
  with_items: "{{ percona_server_dependencies }}"
  tags:
    - percona-server-install-dependencies

- name: install | additional
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
  with_items: "{{ percona_server_install }}"
  tags:
    - percona-server-install-additional
